name: EC2 Auto Off

on:
  schedule:
    # Run every day at 14:30 UTC (20:00 Asia/Colombo)
    - cron: '30 14 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ec2-auto-off:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run EC2 Auto Off
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION || 'us-east-1' }}
        REGIONS: ${{ vars.REGIONS }}
        TAG_KEY: ${{ vars.TAG_KEY || 'auto-off' }}
        TAG_VALUE: ${{ vars.TAG_VALUE || 'true' }}
        HIBERNATE: ${{ vars.HIBERNATE || 'false' }}
        DRY_RUN: ${{ vars.DRY_RUN || 'false' }}
        ALERT_WEBHOOK: ${{ secrets.ALERT_WEBHOOK }}
      run: python ec2_auto_off.py
